/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface PriceData {
    btcUsd: number;
    icpUsd: number;
    updatedAt: bigint;
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface HttpResponsePayload {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface PaymentLinkInfo {
    id: string;
    method: PaymentMethod;
    title: string;
    creator: Principal;
    active: boolean;
    totalReceived: bigint;
    expiresAt?: bigint;
    createdAt: bigint;
    description: string;
    amount: bigint;
    paymentCount: bigint;
}
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<[string, string]>;
    status_code: number;
}
export interface CreateLinkArgs {
    method: PaymentMethod;
    title: string;
    expiresAt?: bigint;
    description: string;
    amount: bigint;
}
export interface Payment {
    id: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: bigint;
    confirmedAt?: bigint;
    txId?: bigint;
    payer: Principal;
    amount: bigint;
    linkId: string;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<[string, string]>;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface ConfirmPaymentArgs {
    blockIndex: bigint;
    linkId: string;
}
export enum PaymentMethod {
    icp = "icp",
    ckbtc = "ckbtc"
}
export enum PaymentStatus {
    expired = "expired",
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    confirmPayment(args: ConfirmPaymentArgs): Promise<Result>;
    createLink(args: CreateLinkArgs): Promise<string>;
    deactivateLink(linkId: string): Promise<void>;
    getCkbtcDepositAddress(linkId: string): Promise<string>;
    getLink(linkId: string): Promise<PaymentLinkInfo | null>;
    getPaymentAddress(linkId: string): Promise<Account | null>;
    getUsdPrices(): Promise<PriceData>;
    http_request(req: HttpRequest): Promise<HttpResponse>;
    linkPaymentHistory(linkId: string): Promise<Array<Payment>>;
    myLinks(): Promise<Array<PaymentLinkInfo>>;
    reactivateLink(linkId: string): Promise<void>;
    stats(): Promise<{
        totalPayments: bigint;
        totalLinks: bigint;
        activeLinks: bigint;
    }>;
    transform(arg0: {
        context: Uint8Array;
        response: HttpResponsePayload;
    }): Promise<HttpResponsePayload>;
}
import type { Account as _Account, CreateLinkArgs as _CreateLinkArgs, Payment as _Payment, PaymentLinkInfo as _PaymentLinkInfo, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Result as _Result } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async confirmPayment(arg0: ConfirmPaymentArgs): Promise<Result> {
        const result = await this.actor.confirmPayment(arg0);
        return from_candid_Result_n1(result);
    }
    async createLink(arg0: CreateLinkArgs): Promise<string> {
        const result = await this.actor.createLink(to_candid_CreateLinkArgs_n3(arg0));
        return result;
    }
    async deactivateLink(arg0: string): Promise<void> {
        const result = await this.actor.deactivateLink(arg0);
        return result;
    }
    async getCkbtcDepositAddress(arg0: string): Promise<string> {
        const result = await this.actor.getCkbtcDepositAddress(arg0);
        return result;
    }
    async getLink(arg0: string): Promise<PaymentLinkInfo | null> {
        const result = await this.actor.getLink(arg0);
        return from_candid_opt_n7(result);
    }
    async getPaymentAddress(arg0: string): Promise<Account | null> {
        const result = await this.actor.getPaymentAddress(arg0);
        return from_candid_opt_n13(result);
    }
    async getUsdPrices(): Promise<PriceData> {
        const result = await this.actor.getUsdPrices();
        return result;
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request(arg0);
        return result;
    }
    async linkPaymentHistory(arg0: string): Promise<Array<Payment>> {
        const result = await this.actor.linkPaymentHistory(arg0);
        return from_candid_vec_n17(result);
    }
    async myLinks(): Promise<Array<PaymentLinkInfo>> {
        const result = await this.actor.myLinks();
        return from_candid_vec_n23(result);
    }
    async reactivateLink(arg0: string): Promise<void> {
        const result = await this.actor.reactivateLink(arg0);
        return result;
    }
    async stats(): Promise<{
        totalPayments: bigint;
        totalLinks: bigint;
        activeLinks: bigint;
    }> {
        const result = await this.actor.stats();
        return result;
    }
    async transform(arg0: {
        context: Uint8Array;
        response: HttpResponsePayload;
    }): Promise<HttpResponsePayload> {
        const result = await this.actor.transform(arg0);
        return result;
    }
}
function from_candid_Account_n14(value: _Account): Account {
    return from_candid_record_n15(value);
}
function from_candid_PaymentLinkInfo_n8(value: _PaymentLinkInfo): PaymentLinkInfo {
    return from_candid_record_n9(value);
}
function from_candid_PaymentMethod_n10(value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n11(value);
}
function from_candid_PaymentStatus_n20(value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n21(value);
}
function from_candid_Payment_n18(value: _Payment): Payment {
    return from_candid_record_n19(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_opt_n12(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n14(value[0]);
}
function from_candid_opt_n16(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(value: [] | [_PaymentLinkInfo]): PaymentLinkInfo | null {
    return value.length === 0 ? null : from_candid_PaymentLinkInfo_n8(value[0]);
}
function from_candid_record_n15(value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n16(value.subaccount))
    };
}
function from_candid_record_n19(value: {
    id: string;
    status: _PaymentStatus;
    method: _PaymentMethod;
    createdAt: bigint;
    confirmedAt: [] | [bigint];
    txId: [] | [bigint];
    payer: Principal;
    amount: bigint;
    linkId: string;
}): {
    id: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: bigint;
    confirmedAt?: bigint;
    txId?: bigint;
    payer: Principal;
    amount: bigint;
    linkId: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n20(value.status),
        method: from_candid_PaymentMethod_n10(value.method),
        createdAt: value.createdAt,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n12(value.confirmedAt)),
        txId: record_opt_to_undefined(from_candid_opt_n22(value.txId)),
        payer: value.payer,
        amount: value.amount,
        linkId: value.linkId
    };
}
function from_candid_record_n9(value: {
    id: string;
    method: _PaymentMethod;
    title: string;
    creator: Principal;
    active: boolean;
    totalReceived: bigint;
    expiresAt: [] | [bigint];
    createdAt: bigint;
    description: string;
    amount: bigint;
    paymentCount: bigint;
}): {
    id: string;
    method: PaymentMethod;
    title: string;
    creator: Principal;
    active: boolean;
    totalReceived: bigint;
    expiresAt?: bigint;
    createdAt: bigint;
    description: string;
    amount: bigint;
    paymentCount: bigint;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n10(value.method),
        title: value.title,
        creator: value.creator,
        active: value.active,
        totalReceived: value.totalReceived,
        expiresAt: record_opt_to_undefined(from_candid_opt_n12(value.expiresAt)),
        createdAt: value.createdAt,
        description: value.description,
        amount: value.amount,
        paymentCount: value.paymentCount
    };
}
function from_candid_variant_n11(value: {
    icp: null;
} | {
    ckbtc: null;
}): PaymentMethod {
    return "icp" in value ? PaymentMethod.icp : "ckbtc" in value ? PaymentMethod.ckbtc : value;
}
function from_candid_variant_n2(value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(value: {
    expired: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "expired" in value ? PaymentStatus.expired : "pending" in value ? PaymentStatus.pending : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_vec_n17(value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n18(x));
}
function from_candid_vec_n23(value: Array<_PaymentLinkInfo>): Array<PaymentLinkInfo> {
    return value.map((x)=>from_candid_PaymentLinkInfo_n8(x));
}
function to_candid_CreateLinkArgs_n3(value: CreateLinkArgs): _CreateLinkArgs {
    return to_candid_record_n4(value);
}
function to_candid_PaymentMethod_n5(value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n6(value);
}
function to_candid_record_n4(value: {
    method: PaymentMethod;
    title: string;
    expiresAt?: bigint;
    description: string;
    amount: bigint;
}): {
    method: _PaymentMethod;
    title: string;
    expiresAt: [] | [bigint];
    description: string;
    amount: bigint;
} {
    return {
        method: to_candid_PaymentMethod_n5(value.method),
        title: value.title,
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none(),
        description: value.description,
        amount: value.amount
    };
}
function to_candid_variant_n6(value: PaymentMethod): {
    icp: null;
} | {
    ckbtc: null;
} {
    return value == PaymentMethod.icp ? {
        icp: null
    } : value == PaymentMethod.ckbtc ? {
        ckbtc: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
