/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export interface ConfirmPaymentArgs { 'blockIndex' : bigint, 'linkId' : string }
export interface CreateLinkArgs {
  'method' : PaymentMethod,
  'title' : string,
  'expiresAt' : [] | [bigint],
  'description' : string,
  'amount' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'status_code' : number,
}
export interface HttpResponsePayload {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Payment {
  'id' : string,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'createdAt' : bigint,
  'confirmedAt' : [] | [bigint],
  'txId' : [] | [bigint],
  'payer' : Principal,
  'amount' : bigint,
  'linkId' : string,
}
export interface PaymentLinkInfo {
  'id' : string,
  'method' : PaymentMethod,
  'title' : string,
  'creator' : Principal,
  'active' : boolean,
  'totalReceived' : bigint,
  'expiresAt' : [] | [bigint],
  'createdAt' : bigint,
  'description' : string,
  'amount' : bigint,
  'paymentCount' : bigint,
}
export type PaymentMethod = { 'icp' : null } |
  { 'ckbtc' : null };
export type PaymentStatus = { 'expired' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface PriceData {
  'btcUsd' : number,
  'icpUsd' : number,
  'updatedAt' : bigint,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type TransferError = {
    'GenericError' : { 'message' : string, 'error_code' : bigint }
  } |
  { 'TemporarilyUnavailable' : null } |
  { 'BadBurn' : { 'min_burn_amount' : bigint } } |
  { 'Duplicate' : { 'duplicate_of' : bigint } } |
  { 'BadFee' : { 'expected_fee' : bigint } } |
  { 'CreatedInFuture' : { 'ledger_time' : bigint } } |
  { 'TooOld' : null } |
  { 'InsufficientFunds' : { 'balance' : bigint } };
export type TransferResult = { 'Ok' : bigint } |
  { 'Err' : TransferError };
export interface _SERVICE {
  'confirmPayment' : ActorMethod<[ConfirmPaymentArgs], Result>,
  'createLink' : ActorMethod<[CreateLinkArgs], string>,
  'deactivateLink' : ActorMethod<[string], undefined>,
  'getCkbtcDepositAddress' : ActorMethod<[string], string>,
  'getLink' : ActorMethod<[string], [] | [PaymentLinkInfo]>,
  'getPaymentAddress' : ActorMethod<[string], [] | [Account]>,
  'getUsdPrices' : ActorMethod<[], PriceData>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'linkPaymentHistory' : ActorMethod<[string], Array<Payment>>,
  'myLinks' : ActorMethod<[], Array<PaymentLinkInfo>>,
  'reactivateLink' : ActorMethod<[string], undefined>,
  'rescueFunds' : ActorMethod<
    [Uint8Array, Account, bigint, Principal],
    TransferResult
  >,
  'stats' : ActorMethod<
    [],
    { 'totalPayments' : bigint, 'totalLinks' : bigint, 'activeLinks' : bigint }
  >,
  'transform' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponsePayload }],
    HttpResponsePayload
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];