/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const ConfirmPaymentArgs = IDL.Record({
    'blockIndex' : IDL.Nat,
    'linkId' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const PaymentMethod = IDL.Variant({ 'icp' : IDL.Null, 'ckbtc' : IDL.Null });
  const CreateLinkArgs = IDL.Record({
    'method' : PaymentMethod,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const PaymentLinkInfo = IDL.Record({
    'id' : IDL.Text,
    'method' : PaymentMethod,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'active' : IDL.Bool,
    'totalReceived' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
    'paymentCount' : IDL.Nat,
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const PriceData = IDL.Record({
    'btcUsd' : IDL.Float64,
    'icpUsd' : IDL.Float64,
    'updatedAt' : IDL.Int,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const PaymentStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'createdAt' : IDL.Int,
    'confirmedAt' : IDL.Opt(IDL.Int),
    'txId' : IDL.Opt(IDL.Nat),
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
    'linkId' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponsePayload = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    'confirmPayment' : IDL.Func([ConfirmPaymentArgs], [Result], []),
    'createLink' : IDL.Func([CreateLinkArgs], [IDL.Text], []),
    'deactivateLink' : IDL.Func([IDL.Text], [], []),
    'getCkbtcDepositAddress' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getLink' : IDL.Func([IDL.Text], [IDL.Opt(PaymentLinkInfo)], ['query']),
    'getPaymentAddress' : IDL.Func([IDL.Text], [IDL.Opt(Account)], ['query']),
    'getUsdPrices' : IDL.Func([], [PriceData], []),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'linkPaymentHistory' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'myLinks' : IDL.Func([], [IDL.Vec(PaymentLinkInfo)], ['query']),
    'reactivateLink' : IDL.Func([IDL.Text], [], []),
    'stats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPayments' : IDL.Nat,
            'totalLinks' : IDL.Nat,
            'activeLinks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'transform' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponsePayload,
          }),
        ],
        [HttpResponsePayload],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };